### ISSUE TITLE
test

### ISSUE THREAD

**Issue by renatamuy** [mauriciovancine/bivarmap#9]
Oi @mauriciovancine 

então, por algum motivo o script de teste não está rodando mais. Semana passada estava rodando normal. O erro:

Error in bivarmap::bivarmap_raster(rasterx = temprec$temp, rastery = temprec$prec,  : 
  unused argument (colourmatrix = colmatrix)

**Comment by bniebuhr** [comment]
Re, 

Eu padronizei o nome do argumento para `colmatrix` entre as várias funções,  pois estava diferente para cada função. Aqui nesse commit  05151e4a8cd70017f36506894d49fe680b1421a1

Talvez devesse ter comentado isso num issue, para registro?

Tenta mudar isso lá no teste.

Além disso, coloquei o script de teste na pasta examples. Acho que podemos deixar isso lá. Ele agora é chamado na documentação da função `bivarmap_map`.

Creio que podemos deixar nessa pasta tanto scripts experimentais quanto esses que formos adicionar na documentação...

**Comment by bniebuhr** [comment]
Depois conta aqui se rolou. Aqui deu.

**Comment by renatamuy** [comment]
@bniebuhr era exatamente isso o problema, Ber! Quando coloquei tudo pra colmatrix, rodou perfeito. Não tinha visto que estava diferente no pacote rs! Valew!
